user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java, user-service/src/main/java/hcmus/alumni/userservice/repository/UserRepository.java, user-service/src/main/java/hcmus/alumni/userservice/utils/ImageUtils.java
hashing image name
add function delete image from url
=> TS adjust post alumni verification

.gitignore, auth-service/src/main/java/hcmus/alumni/authservice/config/CustomUserDetails.java, news-service/src/main/java/hcmus/alumni/news/controller/NewsServiceController.java, news-service/src/main/java/hcmus/alumni/news/model/NewsModel.java, news-service/src/main/java/hcmus/alumni/news/model/UserModel.java, news-service/src/main/java/hcmus/alumni/news/repository/NewsRepository.java, news-service/src/main/java/hcmus/alumni/news/utils/GCPConnectionUtils.java, news-service/src/main/java/hcmus/alumni/news/utils/ImageUtils.java
clean unused imports
add GET most-viewed and hot news apis
=> TS clean and add apis

event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java, event-service/src/main/java/hcmus/alumni/event/repository/EventRepository.java
get most participants and hot events api
=> CN events addition api

news-service/src/main/java/hcmus/alumni/news/controller/NewsServiceController.java, news-service/src/main/java/hcmus/alumni/news/dto/ICommentNewsDto.java, news-service/src/main/java/hcmus/alumni/news/dto/INewsDto.java, news-service/src/main/java/hcmus/alumni/news/model/CommentNewsModel.java, news-service/src/main/java/hcmus/alumni/news/model/NewsModel.java, news-service/src/main/java/hcmus/alumni/news/repository/CommentNewsRepository.java, news-service/src/main/java/hcmus/alumni/news/repository/NewsRepository.java, news-service/src/main/java/hcmus/alumni/news/scheduling/PublishSchedule.java
- Get news comments (excluding children comments)
- Get children comments of a specific comment
- Upload a comment
- Edit a comment
- Delete a comment and its children (if exists)
=> TS news comments apis

news-service/src/main/java/hcmus/alumni/news/controller/NewsServiceController.java, news-service/src/main/java/hcmus/alumni/news/repository/CommentNewsRepository.java, news-service/src/main/java/hcmus/alumni/news/repository/NewsRepository.java
Change parent comment count when post and delete
=> TS News comments adjust logic

event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java, event-service/src/main/java/hcmus/alumni/event/dto/ICommentEventDto.java, event-service/src/main/java/hcmus/alumni/event/dto/IEventDto.java, event-service/src/main/java/hcmus/alumni/event/dto/IParticipantEventDto.java, event-service/src/main/java/hcmus/alumni/event/model/CommentEventModel.java, event-service/src/main/java/hcmus/alumni/event/model/EventModel.java, event-service/src/main/java/hcmus/alumni/event/model/ParticipantEventModel.java, event-service/src/main/java/hcmus/alumni/event/repository/CommentEventRepository.java, event-service/src/main/java/hcmus/alumni/event/repository/EventRepository.java, event-service/src/main/java/hcmus/alumni/event/repository/ParticipantEventRepository.java
1. đổi search events default lấy event từ hiện tại trở đi (có thể lấy all từ trước đến giờ)
2. chỉnh get danh sách participants lấy theo trang
3. thêm api cho user tham gia và bỏ tham gia sự kiện
4. thêm api get, add, update, delete cho events comments
5. clean
=> CN events comments and participants

event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java, event-service/src/main/java/hcmus/alumni/event/repository/EventRepository.java, event-service/src/main/java/hcmus/alumni/event/repository/ParticipantEventRepository.java
1. Get events and Get participated events: isUpcoming > mode: 1 get future, 2 get past, 3 get all
2. Create event and Update event: Can minimum and maximum participants when create and edit an event
=> CN fix events api

.vscode/launch.json, counsel-service/src/main/java/hcmus/alumni/counsel/model/PostAdviseModel.java, counsel-service/src/main/java/hcmus/alumni/counsel/repository/PostAdviseRepository.java
=> Counsel fix logic

hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/utils/ImageUtils.java, news-service/src/main/java/hcmus/alumni/news/utils/ImageUtils.java
check if img src is base64 if it is then save else skip
=> News and Hof save images logic

counsel-service/src/main/java/hcmus/alumni/counsel/common/CommentPostAdvisePermissions.java, counsel-service/src/main/java/hcmus/alumni/counsel/common/PostAdvisePermissions.java, counsel-service/src/main/java/hcmus/alumni/counsel/controller/CounselServiceController.java, counsel-service/src/main/java/hcmus/alumni/counsel/dto/ICommentPostAdviseDto.java, counsel-service/src/main/java/hcmus/alumni/counsel/dto/IPostAdviseDto.java, counsel-service/src/main/java/hcmus/alumni/counsel/model/CommentPostAdviseModel.java, counsel-service/src/main/java/hcmus/alumni/counsel/model/PostAdviseModel.java, counsel-service/src/main/java/hcmus/alumni/counsel/repository/CommentPostAdviseRepository.java, counsel-service/src/main/java/hcmus/alumni/counsel/repository/PostAdviseRepository.java, news-service/src/main/java/hcmus/alumni/news/common/CommentNewsPermissions.java, news-service/src/main/java/hcmus/alumni/news/controller/NewsServiceController.java, news-service/src/main/java/hcmus/alumni/news/dto/ICommentNewsDto.java, news-service/src/main/java/hcmus/alumni/news/model/CommentNewsModel.java, news-service/src/main/java/hcmus/alumni/news/repository/CommentNewsRepository.java
Add permissions which have edit and delete as boolean when returning post advise and comments of post advise and news
=> News and Counsel add fields to returning json

event-service/src/main/java/hcmus/alumni/event/common/CommentEventPermissions.java, event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java, event-service/src/main/java/hcmus/alumni/event/dto/ICommentEventDto.java, event-service/src/main/java/hcmus/alumni/event/dto/IEventDto.java, event-service/src/main/java/hcmus/alumni/event/model/CommentEventModel.java, event-service/src/main/java/hcmus/alumni/event/repository/CommentEventRepository.java, group-service/src/main/java/hcmus/alumni/group/common/CommentPostGroupPermissions.java, group-service/src/main/java/hcmus/alumni/group/common/PostGroupPermissions.java, group-service/src/main/java/hcmus/alumni/group/controller/GroupServiceController.java, group-service/src/main/java/hcmus/alumni/group/dto/ICommentPostGroupDto.java, group-service/src/main/java/hcmus/alumni/group/dto/IGroupDto.java, group-service/src/main/java/hcmus/alumni/group/dto/IGroupMemberDto.java, group-service/src/main/java/hcmus/alumni/group/dto/IInteractPostGroupDto.java, group-service/src/main/java/hcmus/alumni/group/dto/IPostGroupDto.java, group-service/src/main/java/hcmus/alumni/group/dto/IRequestJoinGroupDto.java, group-service/src/main/java/hcmus/alumni/group/dto/ReactRequestDto.java, group-service/src/main/java/hcmus/alumni/group/model/CommentPostGroupModel.java, group-service/src/main/java/hcmus/alumni/group/model/GroupMemberModel.java, group-service/src/main/java/hcmus/alumni/group/model/InteractPostGroupId.java, group-service/src/main/java/hcmus/alumni/group/model/InteractPostGroupModel.java, group-service/src/main/java/hcmus/alumni/group/model/PostGroupModel.java, group-service/src/main/java/hcmus/alumni/group/model/ReactModel.java, group-service/src/main/java/hcmus/alumni/group/repository/CommentPostGroupRepository.java, group-service/src/main/java/hcmus/alumni/group/repository/GroupMemberRepository.java, group-service/src/main/java/hcmus/alumni/group/repository/InteractPostGroupRepository.java, group-service/src/main/java/hcmus/alumni/group/repository/PostGroupRepository.java
1. Mostly fix Group apis' conditions
2. Fix Event apis
3. Add React Post Group (copied from Counsel)
Note: update excel after merge
=> CN Fix logic Event and Group + Add React Post Group

group-service/src/main/java/hcmus/alumni/group/dto/IGroupDto.java
=> CN group add return field

auth-service/src/main/java/hcmus/alumni/authservice/model/RoleModel.java, counsel-service/src/main/java/hcmus/alumni/counsel/config/PreAuthenticatedUserRoleHeaderFilter.java, counsel-service/src/main/java/hcmus/alumni/counsel/controller/CounselServiceController.java, counsel-service/src/main/java/hcmus/alumni/counsel/model/CommentPostAdviseModel.java, counsel-service/src/main/java/hcmus/alumni/counsel/model/PostAdviseModel.java, counsel-service/src/main/java/hcmus/alumni/counsel/repository/CommentPostAdviseRepository.java, counsel-service/src/main/java/hcmus/alumni/counsel/repository/PostAdviseRepository.java, news-service/src/main/java/hcmus/alumni/news/controller/NewsServiceController.java, news-service/src/main/java/hcmus/alumni/news/model/CommentNewsModel.java, news-service/src/main/java/hcmus/alumni/news/repository/CommentNewsRepository.java, user-service/src/main/java/hcmus/alumni/userservice/config/PreAuthenticatedUserRoleHeaderFilter.java, user-service/src/main/java/hcmus/alumni/userservice/controller/RoleServiceController.java, user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java, user-service/src/main/java/hcmus/alumni/userservice/dto/IPermissionDto.java, user-service/src/main/java/hcmus/alumni/userservice/dto/IRoleDto.java, user-service/src/main/java/hcmus/alumni/userservice/dto/IRoleWithoutPermissionsDto.java, user-service/src/main/java/hcmus/alumni/userservice/model/PermissionModel.java, user-service/src/main/java/hcmus/alumni/userservice/model/RoleModel.java, user-service/src/main/java/hcmus/alumni/userservice/repository/PermissionRepository.java, user-service/src/main/java/hcmus/alumni/userservice/repository/RoleRepository.java
Configure Permission-Based Access Control for these services
- User Service
- News Service
- Counsel Service
=> TS Configure Permission-Based Access Control

group-service/src/main/java/hcmus/alumni/group/common/GroupMemberRole.java, group-service/src/main/java/hcmus/alumni/group/common/GroupPermissions.java, group-service/src/main/java/hcmus/alumni/group/config/PreAuthenticatedUserRoleHeaderFilter.java, group-service/src/main/java/hcmus/alumni/group/controller/GroupServiceController.java, group-service/src/main/java/hcmus/alumni/group/dto/IGroupDto.java, group-service/src/main/java/hcmus/alumni/group/dto/IGroupMemberDto.java, group-service/src/main/java/hcmus/alumni/group/dto/IRequestJoinGroupDto.java, group-service/src/main/java/hcmus/alumni/group/dto/IUserDto.java, group-service/src/main/java/hcmus/alumni/group/model/CommentPostGroupModel.java, group-service/src/main/java/hcmus/alumni/group/model/FriendId.java, group-service/src/main/java/hcmus/alumni/group/model/FriendModel.java, group-service/src/main/java/hcmus/alumni/group/model/GroupMemberModel.java, group-service/src/main/java/hcmus/alumni/group/model/GroupModel.java, group-service/src/main/java/hcmus/alumni/group/model/PostGroupModel.java, group-service/src/main/java/hcmus/alumni/group/model/RequestJoinGroupModel.java, group-service/src/main/java/hcmus/alumni/group/repository/CommentPostGroupRepository.java, group-service/src/main/java/hcmus/alumni/group/repository/GroupMemberRepository.java, group-service/src/main/java/hcmus/alumni/group/repository/GroupRepository.java, group-service/src/main/java/hcmus/alumni/group/repository/PostGroupRepository.java, group-service/src/main/java/hcmus/alumni/group/repository/RequestJoinGroupRepository.java
Tui tính merge này vô để bên front đỡ đợi, PBAC cho Events tui sẽ để pr kế
Ngoài api tạo với xóa group là permission based, thì mấy api ở trong group tui để là role based
=> CN Group configure permission and misc changes

news-service/src/main/java/hcmus/alumni/news/controller/NewsServiceController.java, news-service/src/main/java/hcmus/alumni/news/model/NewsModel.java, news-service/src/main/java/hcmus/alumni/news/model/TagModel.java, news-service/src/main/java/hcmus/alumni/news/repository/NewsRepository.java, news-service/src/main/java/hcmus/alumni/news/repository/TagRepository.java, user-service/src/main/java/hcmus/alumni/userservice/controller/RoleServiceController.java
1. Thay đổi TagModel
2. Thay đổi cách thêm Tag khi tạo và chỉnh sửa bài viết
3. Thay đổi params khi tìm kiếm bài viết
=> News adjust Tags

counsel-service/src/main/java/hcmus/alumni/counsel/controller/CounselServiceController.java, counsel-service/src/main/java/hcmus/alumni/counsel/repository/PostAdviseRepository.java, news-service/src/main/java/hcmus/alumni/news/controller/NewsServiceController.java
Fix get posts by tag names
Add new api to get posts of a user
=> Counsel fixing and get posts of a user

counsel-service/src/main/java/hcmus/alumni/counsel/controller/CounselServiceController.java, counsel-service/src/main/java/hcmus/alumni/counsel/model/PostAdviseModel.java
allowAddOptions and allowMultipleVotes returning values not correct
=> Counsel fixing bug

database/script.sql
Chắc là mình phải tạo 1 file excel để quy định entity type id
=> CN Add notification tables to DB script

message-service/src/main/java/hcmus/alumni/message/controller/MessageServiceController.java, message-service/src/main/java/hcmus/alumni/message/service/InboxService.java
Refactor extractUserIds method in InboxService to include self user ID
=> Adjust logic of sending msg

counsel-service/src/main/java/hcmus/alumni/counsel/controller/CounselServiceController.java, counsel-service/src/main/java/hcmus/alumni/counsel/dto/response/ICommentWithPostDto.java, counsel-service/src/main/java/hcmus/alumni/counsel/repository/CommentPostAdviseRepository.java, news-service/src/main/java/hcmus/alumni/news/controller/NewsServiceController.java, news-service/src/main/java/hcmus/alumni/news/dto/ICommentNewsDto.java, news-service/src/main/java/hcmus/alumni/news/repository/CommentNewsRepository.java
1. News
- Add API endpoint to retrieve a specific comment
2. Counsel
- Add API endpoint to retrieve comments of a user
- Add API endpoint to retrieve a specific comment
=> Add API Endpoints to News and Counsel

database/script.sql, event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java, group-service/src/main/java/hcmus/alumni/group/controller/GroupServiceController.java, user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java, user-service/src/main/java/hcmus/alumni/userservice/dto/UserSearchDto.java, user-service/src/main/java/hcmus/alumni/userservice/repository/UserRepository.java
Fix db script syntax
Add API endpoint for retrieving a single user for user management in User Service Adjust UserSearchDto
=> Fix and Add new API endpoint

event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java, event-service/src/main/java/hcmus/alumni/event/dto/ICommentEventDto.java, event-service/src/main/java/hcmus/alumni/event/repository/CommentEventRepository.java, group-service/src/main/java/hcmus/alumni/group/controller/GroupServiceController.java, group-service/src/main/java/hcmus/alumni/group/dto/response/ICommentPostGroupDto.java, group-service/src/main/java/hcmus/alumni/group/repository/CommentPostGroupRepository.java
Add API to get specific comment in Event and Group
=> CN Event, Group Get specific comment

counsel-service/src/main/java/hcmus/alumni/counsel/config/FirebaseConfig.java, counsel-service/src/main/java/hcmus/alumni/counsel/controller/CounselServiceController.java, counsel-service/src/main/java/hcmus/alumni/counsel/repository/UserRepository.java, counsel-service/src/main/java/hcmus/alumni/counsel/utils/FirebaseService.java, event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java, event-service/src/main/java/hcmus/alumni/event/repository/UserRepository.java, event-service/src/main/java/hcmus/alumni/event/utils/FirebaseService.java, group-service/src/main/java/hcmus/alumni/group/controller/GroupServiceController.java, group-service/src/main/java/hcmus/alumni/group/utils/FirebaseService.java, news-service/src/main/java/hcmus/alumni/news/controller/NewsServiceController.java, news-service/src/main/java/hcmus/alumni/news/repository/UserRepository.java, news-service/src/main/java/hcmus/alumni/news/utils/FirebaseService.java
1. Update deprecated method in FirebaseService
2. Fix null fields in Push Notification
=> CN fix Push Notification

message-service/src/main/java/hcmus/alumni/message/controller/MessageServiceController.java, message-service/src/main/java/hcmus/alumni/message/repostiory/InboxRepository.java, message-service/src/main/java/hcmus/alumni/message/service/InboxService.java
Add search functionality to getInboxes API endpoint
=> Messages Add functionality

notification-service/src/main/resources/application.properties
Duplicate port vs counsel service
Change noti service port to 9009
=> Notification Change service port

counsel-service/src/main/java/hcmus/alumni/counsel/utils/FirebaseService.java, event-service/src/main/java/hcmus/alumni/event/utils/FirebaseService.java, group-service/src/main/java/hcmus/alumni/group/utils/FirebaseService.java, news-service/src/main/java/hcmus/alumni/news/utils/FirebaseService.java
Bên mobile hiện tại đang tự động lấy nguyên cái json để hiển thị thông báo. Và không trích một mình cái notificationMessage để hiện được. 
Nên tui phải dời đống json về lại data.body và notification.body bây giờ là notificationMessage.
Có thể check excel để xem Push Notification được nhận trông như nào. Hoặc inbox tui cũng được.
=> CN Fix Push Notification for mobile

message-service/src/main/java/hcmus/alumni/message/controller/MessageServiceController.java, message-service/src/main/java/hcmus/alumni/message/service/InboxService.java
Add inbox information to message response
=> Messages Adjust API response

group-service/src/main/java/hcmus/alumni/group/repository/notification/NotificationChangeRepository.java, message-service/pom.xml, message-service/src/main/java/hcmus/alumni/message/config/FirebaseConfig.java, message-service/src/main/java/hcmus/alumni/message/controller/MessageServiceController.java, message-service/src/main/java/hcmus/alumni/message/model/UserSubscriptionTokenId.java, message-service/src/main/java/hcmus/alumni/message/model/UserSubscriptionTokenModel.java, message-service/src/main/java/hcmus/alumni/message/repostiory/InboxMemberRepository.java, message-service/src/main/java/hcmus/alumni/message/repostiory/UserSubscriptionTokenRepository.java, message-service/src/main/java/hcmus/alumni/message/service/FirebaseService.java, message-service/src/main/resources/application.properties
1. Thêm Push Notification cho Message Service
Phần message tui chỉ thêm push notification chứ không lưu xuống mấy bảng trong db.
Title sẽ là tên người gửi, Content thì sẽ switch case tùy theo message type.
Chi tiết body thì có thể xem thêm tại [tab Tổng của Danh sách quy hoạch thông báo](https://docs.google.com/spreadsheets/d/1uVlD7WGejFrwLiFjP2fHUYcgmm9i4Y-3zDvL8K1bf9c/edit?gid=6874541#gid=6874541)
2. Fix lỗi bên Group service
Fix được cái lỗi mà đc phê duyệt > out group > join lại > đc phê duyệt lại thì bị lỗi
=> CN Message Push Notification

notification-service/src/main/java/hcmus/alumni/notification/controller/NotificationServiceController.java, user-service/pom.xml, user-service/src/main/java/hcmus/alumni/userservice/common/NotificationType.java, user-service/src/main/java/hcmus/alumni/userservice/config/FirebaseConfig.java, user-service/src/main/java/hcmus/alumni/userservice/controller/UserServiceController.java, user-service/src/main/java/hcmus/alumni/userservice/model/UserSubscriptionTokenId.java, user-service/src/main/java/hcmus/alumni/userservice/model/UserSubscriptionTokenModel.java, user-service/src/main/java/hcmus/alumni/userservice/model/notification/EntityTypeModel.java, user-service/src/main/java/hcmus/alumni/userservice/model/notification/NotificationChangeModel.java, user-service/src/main/java/hcmus/alumni/userservice/model/notification/NotificationModel.java, user-service/src/main/java/hcmus/alumni/userservice/model/notification/NotificationObjectModel.java, user-service/src/main/java/hcmus/alumni/userservice/model/notification/StatusNotificationModel.java, user-service/src/main/java/hcmus/alumni/userservice/repository/UserSubscriptionTokenRepository.java, user-service/src/main/java/hcmus/alumni/userservice/repository/notification/EntityTypeRepository.java, user-service/src/main/java/hcmus/alumni/userservice/repository/notification/NotificationChangeRepository.java, user-service/src/main/java/hcmus/alumni/userservice/repository/notification/NotificationObjectRepository.java, user-service/src/main/java/hcmus/alumni/userservice/repository/notification/NotificationRepository.java, user-service/src/main/java/hcmus/alumni/userservice/utils/FirebaseService.java, user-service/src/main/java/hcmus/alumni/userservice/utils/NotificationService.java, user-service/src/main/resources/application.properties
Send notification when:
1. A sends request friend to B
2. A accepts request friend of B
3. A denies request friend of B
=> CN friend notification

api-gateway/Dockerfile, api-gateway/pom.xml, api-gateway/src/main/java/hcmus/alumni/apigateway/AuthenticationGatewayFilterFactory.java, api-gateway/src/main/java/hcmus/alumni/apigateway/filter/ApiEndpoint.java, api-gateway/src/main/java/hcmus/alumni/apigateway/filter/RouteValidator.java, auth-service/Dockerfile, counsel-service/Dockerfile, docker-compose.yml, event-service/Dockerfile, event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java, group-service/Dockerfile, hall-of-fame-service/Dockerfile, hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/controller/HallOfFameServiceController.java, hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/repository/HallOfFameRepository.java, message-service/Dockerfile, news-service/Dockerfile, news-service/src/main/java/hcmus/alumni/news/controller/NewsServiceController.java, notification-service/Dockerfile, service-discovery/Dockerfile, user-service/Dockerfile
Điều chỉnh Dockerfile, h có thêm build step
Hoàn thành docker-compose.yml
Whitelist một số APIs ko cần đăng nhập vẫn gọi được
- HttpMethod.GET, "/news"
- HttpMethod.GET, "/news/{id}"
- HttpMethod.GET, "/news/{id}/related"
- HttpMethod.GET, "/news/hot"
- HttpMethod.GET, "/news/{id}/comments"
- HttpMethod.GET, "/news/comments/{commentId}/children"
- HttpMethod.GET, "/news/{newsId}/comments/{commentId}"
- HttpMethod.GET, "/events"
- HttpMethod.GET, "/events/{id}"
- HttpMethod.GET, "/events/hot"
- HttpMethod.GET, "/events/is-participated"
- HttpMethod.GET, "/events/{id}/participants"
- HttpMethod.GET, "/events/{id}/comments"
- HttpMethod.GET, "/events/comments/{commentId}/children"
- HttpMethod.GET, "/events/{eventId}/comments/{commentId}"
- HttpMethod.GET, "/hof"
- HttpMethod.GET, …
=> Whitelist some APIs

auth-service/Dockerfile, auth-service/pom.xml, auth-service/src/main/resources/application.properties, counsel-service/src/main/java/hcmus/alumni/counsel/controller/CounselServiceController.java, counsel-service/src/main/java/hcmus/alumni/counsel/dto/response/CommentPostAdviseDto.java, docker-compose.yml, hall-of-fame-service/src/main/java/hcmus/alumni/halloffame/repository/HallOfFameRepository.java, news-service/pom.xml, news-service/src/main/java/hcmus/alumni/news/config/ModelMapperConfig.java, news-service/src/main/java/hcmus/alumni/news/controller/NewsServiceController.java, news-service/src/main/java/hcmus/alumni/news/dto/CommentNewsDto.java
Post comment APIs for news and counsel now return saved comment
=> Fix Docker and Ajust APIs

event-service/pom.xml, event-service/src/main/java/hcmus/alumni/event/config/ModelMapperConfig.java, event-service/src/main/java/hcmus/alumni/event/controller/EventServiceController.java, event-service/src/main/java/hcmus/alumni/event/dto/CommentEventDto.java, event-service/src/main/java/hcmus/alumni/event/dto/IEventDto.java, event-service/src/main/java/hcmus/alumni/event/model/EventModel.java, event-service/src/main/java/hcmus/alumni/event/model/ParticipantEventModel.java, event-service/src/main/java/hcmus/alumni/event/repository/EventRepository.java, group-service/src/main/java/hcmus/alumni/group/controller/GroupServiceController.java, group-service/src/main/java/hcmus/alumni/group/dto/response/CommentPostGroupDto.java
1. Adjust comment apis for event and group service
2. Add transient field to check request user is participating the result events + Remove the check is participated event api. (Nói chung là thay vì gọi api 1 cái để lấy danh sách, 1 cái để check user có tham gia thì bây giờ chỉ cần gọi mỗi api lấy danh sách thôi)
3. Chỉnh lại tabs và xóa vài import không dùng
=> CN adjust event group apis
